### ISSUE TITLE
Removing one backtick from vignette smashr.rmd line 740 allows vignette creation

### ISSUE THREAD

**Issue by chris-english** [stephenslab/smashr#5]
Smash.rmd line 731 has a 3 back tick fence, but the closing fence at line 740 has 4. Removing the extra back tick allows the vignette to build.  Then, as it takes a while to run (I felt warned by install instructions - took about an hour), perhaps approaches as discussed [heavy computational vignettes strategies](https://stackoverflow.com/questions/28961431/computationally-heavy-r-vignettes) might be in order.

**Comment by stephens999** [comment]
thanks for the bug report! addressed by c3f2e8e
